name: Run Postman Collection

on:
  push:
    branches: [main]  # حدد الفروع لتشغيل سير العمل عند حدوث push
  pull_request:
    branches: [main]

jobs:
  run-collection-without-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # هذا الإصدار جيد لكن تأكد من وجود التحديثات الأخرى

    - name: Install Node.js
      uses: actions/setup-node@v4  # تحديث إلى الإصدار 4
      with:
        node-version: '20'  # استخدم الإصدار 20 من Node.js

    - name: Install Newman
      run: npm install -g newman

    - name: Install htmlextra reporter
      run: npm install -g newman-reporter-htmlextra

    - name: Create newman directory
      run: mkdir -p newman 

    - name: Run Postman Collection
      run: |
        echo "Running Postman collection using Newman..."
        newman run "Trello API.postman_collection.json" \
                   --reporters cli,htmlextra \
                   --reporter-htmlextra-export newman/report.html

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v4  # تحديث إلى الإصدار 4
      with:
        name: postman-report
        path: newman/report.html
